2.b) Use a computer to find the optimal solution to this quadratic program.

In [80]:
# Import packages.
import cvxpy as cp
import numpy as np

# Input data.
Q = [[1,2],[3,4]]
c = [6,7]
a = [[2],[1]]
b = 5

# Define and solve the CVXPY problem.
x = cp.Variable(2)
prob = cp.Problem(cp.Minimize(cp.norm(Q @ x - c, p=2)),
                  [a @ x == b])
prob.solve()

# Print result.
print("\nThe optimal value is", prob.value)
print("The optimal x is")
print(x.value)
print("The min norm is ", cp.norm(Q @ x - c, p=2).value)


The optimal value is 1.4084056789720465
The optimal x is
[2.01639344 0.96721311]
The min norm is  1.4084056792618551


3.a) design an algorithm which, given a point $x \in R^n$, determines whether the point $x$ is in $\Omega=\{AX\le b\}$

In [81]:
# Import packages.
import cvxpy as cp
import numpy as np

# Generate data.
m = 5
n = 6
np.random.seed(1) # different result for different seed number
A = np.random.randn(m, n)
b = np.random.randn(m)

# Define the membership oracle problem
x = np.array([1,2,3,4,5,6]) # may change
if sum(A @ x <=b)==m:
 print(x, " is in the set \u03A9")
else:
  print(x, "is not in the set \u03A9")



[1 2 3 4 5 6] is not in the set Ω


3.b) A projection oracle
 


In [82]:
### membership oracle

# Import packages.
import cvxpy as cp
import numpy as np

# Generate data.
m = 5
n = 6
np.random.seed(1) # different result for different seed number
A = np.random.randn(m, n)
b = np.random.randn(m)

# Define the projection oracle problem
x = np.array([1,2,3,4,5,6]) # may change
z = cp.Variable(n)
prob = cp.Problem(cp.Minimize(cp.norm(z - x, p=2)),
                  [A @ z <=b])
prob.solve()

# Find project point y
y = z.value

# Print result.
print("\nThe optimal value is", prob.value)
print("The project point y is")
print(z.value)



The optimal value is 6.3150937548917065
The project point y is
[ 0.29759153  0.88850126  6.14877766  2.46470592 -0.01410879  5.14070568]


3.c) Implement above algorithm in specific example.

In [79]:
### membership oracle

# Import packages.
import cvxpy as cp
import numpy as np

# Generate data.
A = [[4,1,1,0],[2,3,0,0]]
b = [5,4,0,0]

# Define the projection oracle problem
x = np.array([1,2]) # may change
z = cp.Variable(2)
prob = cp.Problem(cp.Minimize(cp.norm(z - x, p=2)),
                  [A @ z <=b])
prob.solve()

# Find project point y
y = z.value

# Print result.
print("\nThe optimal value is", prob.value)
print("The project point y is")
print(z.value)


The optimal value is 1.2018504250508673
The project point y is
[1.53733827e-11 1.33333333e+00]


In [84]:
### membership oracle

# Import packages.
import cvxpy as cp
import numpy as np

# Generate data.
A = np.array([[4,2],[1,3],[1,0],[0,1]])
b = np.array([5,4,0,0])

# Define the projection oracle problem
x = np.array([1,2]) # may change
z = cp.Variable(2)
prob = cp.Problem(cp.Minimize(cp.norm(z - x, p=2)),
                  [A @ z <=b])
prob.solve()

# Find project point y
y = z.value

# Print result.
print("\nThe optimal value is", prob.value)
print("The project point y is")
print(z.value)


The optimal value is 2.236067977004352
The project point y is
[3.32904752e-11 1.63899869e-11]


5.b) Find the optimal solution to the linear program

In [83]:
# Import packages.
import cvxpy as cp
import numpy as np

# input data
R = [[300,160,360],[220,130,280],[100,80,140]]
B = [[4,8,3],[8,13,10],[22,20,18]]
a = [1,1,1]
b = [[1],[1],[1]]
c = [[1],[0],[1]]
d = [[0],[1],[1]]
n = 3

# Define and solve rhe CVXPY problem.
X = cp.Variable((n,n))
middle = R*X
prob = cp.Problem(cp.Maximize([sum(x) for x in zip(*middle)][0]+[sum(x) for x in zip(*middle)][1]+[sum(x) for x in zip(*middle)][2]),
                  [[sum(x) for x in zip(*X)][0]+[sum(x) for x in zip(*X)][2]<= 30,
                   [sum(x) for x in zip(*X)][1]+[sum(x) for x in zip(*X)][2]<= 30,
                   X <= B,
                   X >= 0])
prob.solve()

# Print result
print("\nThe optimal value is", prob.value)
print("A solution X is")
print(X.value)


The optimal value is 32549.99999738011
A solution X is
[[ 4.00000000e+00  7.99999999e+00  1.50000000e+01]
 [ 8.00000000e+00  7.00000000e+00  1.74932855e-09]
 [ 2.99999999e+00  6.15128025e-09 -1.82024916e-09]]
